name: 'create-env-file'
description: 'Create a .env file from a json extraction of github environment variables'

branding:
  icon: 'code'
  color: 'green'

inputs:
  variables:
    description: 'Github variables in json format'
    required: false
  secrets:
    description: 'Github secrets in json format'
    required: false
  output-name:
    description: 'Name of the newly created env file'
    required: false
    default: .env

runs:
  using: 'composite'
  steps:
  - name: 'create-env-file'
    env:
      VARIABLES: '${{ inputs.variables }}'
      SECRETS: '${{ inputs.secrets }}'
      OUTPUT_NAME: '${{ inputs.output-name }}'
    shell: sh
    run: |
      apt-get install -y jq
      $GITHUB_ACTION_PATH/scripts/create_env_file.sh
